### ISSUE TITLE
GeoJSON FeatureCollection breaks map if it contains Points without "type" property

### ISSUE THREAD

**Issue by romankaravia** [nzzdev/Q-locator-map#49]
An error is thrown here if type is `undefined`: https://github.com/nzzdev/Q-locator-map/blob/e411446cf0e6bfa222a8ce427c23ec619b2cd43b/scripts_src/helpers.js#L337

### Broken example

Example that reproduces the issue: https://q.st-staging.nzz.ch/item/6dcf203a5c5f74b61aeea0cb0ee4b2cb

FeatureCollection:
```
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          37.63916,
          55.764213
        ]
      },
      "properties": {
        "name": "Moskau"
      }
    }
  ]
}
```

### Workaround

Same example with property `"type": "foo"` (workaround): https://q.st-staging.nzz.ch/item/6dcf203a5c5f74b61aeea0cb0ee4a9f5

**Comment by mephinet** [comment]
Sorry for opening this issue again, @manuelroth . I run into the same issue when importing the data from https://www.data.gv.at/katalog/dataset/covid-19-checkboxen-wien/resource/5ddc934f-2ffb-4cd1-97d0-3135fcdef978 (this links to the official geo data server of the city of Vienna). The q_locator_map fails when rendering this Feature List with:
TypeError: Cannot read property 'includes' of undefined
As far as I can tell, `type` is set correctly:
```
"features": [
        {
            "type": "Feature",
            "id": "...",
            "geometry": {
                "type": "Point",
               ...
        }
        },
```

**Comment by manuelroth** [comment]
Hi @mephinet,
The `type` property has to be set within the `properties` object of the feature. See this locator map in our demo instance as a reference: [https://editor.q.tools/editor/locator_map/e9046b127bd99afc9cd208b94d2c1dfe](https://editor.q.tools/editor/locator_map/e9046b127bd99afc9cd208b94d2c1dfe)
```json
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": { "type": "Point", "coordinates": [9.7872147, 46.4007338] },
      "properties": {
        "type": "point",
        "label": "Sils im Engadin/Segl",
        "labelPosition": "right",
        "useForInitialView": true
      }
    }
  ]
}
```
The locator map tool requires that the type property is set for Point-Features. I am curious. Are you currently using Q for a project?

**Comment by mephinet** [comment]
@manuelroth awesome, thank you every much for the explanation, which helps me understand which type (of all the types in the JSON) we're talking about, and why you require it even though it's not required by the GeoJSON standard.
I want to investigate whether Q would be of help at $work - I'll contact you if we proceed that route!

**Comment by manuelroth** [comment]
I see. Thats awesome. Yes let me know. I am happy to give more information.
